version: '3'
services:

  backend:
    build: .
    container_name: data-in-cloud-app
    links:
      - mongo
    depends_on:
      - postgres
      - mongo
    ports:
      - "8087:8080"

  postgres:
    image: "postgres:14.11"
    container_name: postgres-database
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=DataInCloudMig
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - HOST_URL=host.docker.internal

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    ports:
      - "27035:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

